dataset:
  num_workers: 6
  root_dir: '/media/future/Rapido/NIPS4B_BIRD_CHALLENGE_TRAIN_TEST_WAV/birds-generation-classification/'
  train_path: '${dataset.root_dir}/cleaned_train.txt'
  val_path: '${dataset.root_dir}/cleaned_test.txt'
  test_path: '${dataset.root_dir}/cleaned_test.txt'
  lmdb_path: ''

  batch_size: 32
  classes_name: 
      # - Carcan_call
      # - Carcar_call
      # - Galcri_call
      # - Parmaj_call
      # - Erirub_call
      # - Sylmel_call
    - Erirub_song
    - Turphi_song
    - Turmer_call
    - Parate_song
    - Sylcan_song
    - Galcri_call
    - Cetcet_song
    - Alaarv_song
    - Sylcan_call
    - Serser_song

  augmentation_mode:
    # - masking
    # - timeMasking
    # - freqMasking
    # - mixup
    # - image_base
    # - input_noise
    # - input_dropout
    # - spec_stretching

  resize: false
  return_tuple: true
  return_tuple_of3: true
  sr: 22050
  use_mel: true
  use_cache: false
  use_rgb: true
